[package]
name = "rustium_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "2.1"
dialoguer = "0.11"
indicatif = "0.17"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time"] }